[goldmark]
  [goldmark.parser]
    autoHeadingID = true
    autoHeadingIDType = "github"
  [goldmark.renderer]
    unsafe = true
    hardWraps = false
    xHTML = false
    
[highlight]
  codeFences = true
  guessSyntax = true
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  noHl = false
  style = "monokai"
  tabWidth = 4
  
[tableOfContents]
  endLevel = 3
  ordered = false
  startLevel = 2
  
[markup.goldmark.extensions]
  definitionList = true
  footnote = true
  linkify = true
  strikethrough = true
  table = true
  taskList = true
  typographer = true

[markup.goldmark.renderer]
  unsafe = true
  
[markup.tableOfContents]
  endLevel = 3
  ordered = false
  startLevel = 2
